# =======================================================
# DEPLOYMENT SCRIPT: Windows Medical Workstation Bootstrap
# Description: Configures host firewall, provisions Winlogbeat, 
# and establishes continuous log shipping to the central ELK stack.
# OS Target: Windows Server 2016
# =======================================================

# AI GENERATED ENTIRELY(barely modified), I dont know PowerShell, Generated by Claude AI, and Gemeini AI, rigorously tested and error checked by me
# Winlogbeat installer for Hospital Honeypot - Windows Server 2012 R2
# Pulls from S3 bucket, installs Winlogbeat, ships logs to The Brain (10.0.2.10)

# Log everything - if this script fails, C:\bootstrap_log.txt will tell you exactly where
Start-Transcript -Path "C:\bootstrap_log.txt" -Append
Write-Host "=== Hospital Honeypot Windows Bootstrap Starting ==="

# -------------------------------------------------------
# 1. Host Firewall Configuration
# -------------------------------------------------------
# Allow inbound SMB (445) to expose the legacy file-sharing vulnerability decoy
# Allow inbound ICMP to permit diagnostic pinging from The Brain
Write-Host "Configuring firewall rules..."
netsh advfirewall firewall add rule name="Allow SMB Inbound" dir=in action=allow protocol=TCP localport=445
netsh advfirewall firewall add rule name="Allow ICMP Inbound" protocol=icmpv4 dir=in action=allow
Write-Host "Firewall rules applied."

# -------------------------------------------------------
# 2. Download Winlogbeat
# -------------------------------------------------------
Write-Host "Downloading Winlogbeat..."

# Enforce TLS 1.2 to satisfy modern cryptographic requirements for Elastic's artifact servers
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

$zipUrl  = "https://artifacts.elastic.co/downloads/beats/winlogbeat/winlogbeat-8.10.2-windows-x86_64.zip"
$zipDest = "C:\winlogbeat.zip"
$installDir = "C:\winlogbeat"

try {
    # -UseBasicParsing circumvents the Internet Explorer first-run initialization hang
    Invoke-WebRequest -Uri $zipUrl -OutFile $zipDest -UseBasicParsing
    Write-Host "Download complete."
} catch {
    Write-Host "ERROR: Download failed - $_"
    Stop-Transcript
    exit 1
}

# -------------------------------------------------------
# 3. Extraction
# -------------------------------------------------------
Write-Host "Extracting Winlogbeat..."

# Utilizing the native .NET ZipFile class for robust, dependency-free extraction
Add-Type -AssemblyName System.IO.Compression.FileSystem
[System.IO.Compression.ZipFile]::ExtractToDirectory($zipDest, "C:\")

# Standardize the directory name for service installation mapping
if (Test-Path "C:\winlogbeat-8.10.2-windows-x86_64") {
    Rename-Item "C:\winlogbeat-8.10.2-windows-x86_64" $installDir
    Write-Host "Extracted to $installDir"
} else {
    Write-Host "ERROR: Extracted folder not found - check zip contents"
    Stop-Transcript
    exit 1
}

# -------------------------------------------------------
# 4. Write winlogbeat.yml (YAML Generation)
# -------------------------------------------------------
Write-Host "Writing winlogbeat.yml..."

# IMPORTANT: Strict left-margin alignment is required to maintain valid YAML syntax
$config = @"
winlogbeat.event_logs:
  - name: Application
  - name: Security
  - name: System

output.logstash:
  hosts: ["10.0.2.10:5044"]
"@

# Write file without a Byte Order Mark (BOM) to prevent YAML parsing fatal errors
[System.IO.File]::WriteAllText("$installDir\winlogbeat.yml", $config, [System.Text.Encoding]::UTF8)
Write-Host "winlogbeat.yml written."

# -------------------------------------------------------
# 5. Install and Start the Service
# -------------------------------------------------------
Write-Host "Installing Winlogbeat service..."

# Set-Location is utilized over 'cd' for reliability in non-interactive sessions
Set-Location $installDir

# Bypass execution policy specifically for the Elastic installation script
PowerShell.exe -ExecutionPolicy Bypass -File "$installDir\install-service-winlogbeat.ps1"

Write-Host "Starting Winlogbeat service..."
Start-Service winlogbeat

# Verify it actually started - if not, log the failure
$svc = Get-Service -Name winlogbeat -ErrorAction SilentlyContinue
if ($svc.Status -eq "Running") {
    Write-Host "SUCCESS: Winlogbeat is running and shipping logs to 10.0.2.10:5044"
} else {
    Write-Host "WARNING: Winlogbeat service did not start - check $installDir\logs\"
}

Write-Host "=== Bootstrap Complete ==="
Stop-Transcript