# AI GENERATED ENTIRELY, I dont know PowerShell, this needs hands on testing, Generated by Claude AI

# Winlogbeat installer for Hospital Honeypot - Windows Server 2012 R2
# Pulls from S3 bucket, installs Winlogbeat, ships logs to The Brain (10.0.2.10)

# Log everything - if this script fails, C:\bootstrap_log.txt will tell you exactly where
Start-Transcript -Path "C:\bootstrap_log.txt" -Append
Write-Host "=== Hospital Honeypot Windows Bootstrap Starting ==="

# -------------------------------------------------------
# 1. Firewall Rules
# Open SMB (445) so the validation script knocks are visible
# Open ICMP so the Brain can ping this host
# -------------------------------------------------------
Write-Host "Configuring firewall rules..."
netsh advfirewall firewall add rule name="Allow SMB Inbound" dir=in action=allow protocol=TCP localport=445
netsh advfirewall firewall add rule name="Allow ICMP Inbound" protocol=icmpv4 dir=in action=allow
Write-Host "Firewall rules applied."

# -------------------------------------------------------
# 2. Download Winlogbeat
# -UseBasicParsing avoids the IE first-run dialog bug on 2012 R2
# -------------------------------------------------------
Write-Host "Downloading Winlogbeat..."
$zipUrl  = "https://artifacts.elastic.co/downloads/beats/winlogbeat/winlogbeat-8.10.2-windows-x86_64.zip"
$zipDest = "C:\winlogbeat.zip"
$installDir = "C:\winlogbeat"

try {
    Invoke-WebRequest -Uri $zipUrl -OutFile $zipDest -UseBasicParsing
    Write-Host "Download complete."
} catch {
    Write-Host "ERROR: Download failed - $_"
    Stop-Transcript
    exit 1
}

# -------------------------------------------------------
# 3. Extract
# Expand-Archive doesnt exist in PowerShell 3.0/4.0 (which is what 2012 R2 ships with)
# Using .NET ZipFile class instead for compatibility
# -------------------------------------------------------
Write-Host "Extracting Winlogbeat..."
Add-Type -AssemblyName System.IO.Compression.FileSystem
[System.IO.Compression.ZipFile]::ExtractToDirectory($zipDest, "C:\")

# Rename the versioned folder to something clean
if (Test-Path "C:\winlogbeat-8.10.2-windows-x86_64") {
    Rename-Item "C:\winlogbeat-8.10.2-windows-x86_64" $installDir
    Write-Host "Extracted to $installDir"
} else {
    Write-Host "ERROR: Extracted folder not found - check zip contents"
    Stop-Transcript
    exit 1
}

# -------------------------------------------------------
# 4. Write winlogbeat.yml
# IMPORTANT: Here-string content must be flush against the LEFT MARGIN
# Any leading spaces = broken YAML = Winlogbeat refuses to start
# -------------------------------------------------------
Write-Host "Writing winlogbeat.yml..."
$config = @"
winlogbeat.event_logs:
  - name: Application
  - name: Security
  - name: System

output.logstash:
  hosts: ["10.0.2.10:5044"]
"@

# Write with no BOM - Winlogbeat's YAML parser chokes on UTF-8 BOM
[System.IO.File]::WriteAllText("$installDir\winlogbeat.yml", $config, [System.Text.Encoding]::UTF8)
Write-Host "winlogbeat.yml written."

# -------------------------------------------------------
# 5. Install and Start the Service
# Set-Location (cd equivalent) is more reliable than cd in non-interactive sessions
# ExecutionPolicy Bypass is required - 2012 R2 defaults to Restricted
# -------------------------------------------------------
Write-Host "Installing Winlogbeat service..."
Set-Location $installDir
PowerShell.exe -ExecutionPolicy Bypass -File "$installDir\install-service-winlogbeat.ps1"

Write-Host "Starting Winlogbeat service..."
Start-Service winlogbeat

# Verify it actually started - if not, log the failure
$svc = Get-Service -Name winlogbeat -ErrorAction SilentlyContinue
if ($svc.Status -eq "Running") {
    Write-Host "SUCCESS: Winlogbeat is running and shipping logs to 10.0.2.10:5044"
} else {
    Write-Host "WARNING: Winlogbeat service did not start - check $installDir\logs\"
}

Write-Host "=== Bootstrap Complete ==="
Stop-Transcript